sabotage + fix exit code

diff --git a/.github/workflows/cicd-wkf.yml b/.github/workflows/cicd-wkf.yml
--- a/.github/workflows/cicd-wkf.yml
+++ b/.github/workflows/cicd-wkf.yml
@@ -128,10 +128,10 @@ jobs:
       - 
         name: Check container logs
         run: |
-          set flag-ctl=0
-          kubectl logs -l app=${{ env.DEPLOYMENT_NAME }} | grep -qEi 'fail|err' && (echo "found errors, proceeding to rollout..." && kubectl rollout undo deployment/${{ env.DEPLOYMENT_NAME }} && set flag-ctl=1) || (echo "No errors found in logs.")
-          echo "$flag-ctl"
-          echo $flag-ctl
-          echo [ "$flag-ctl" = "1" ]
-          [ "$flag-ctl" = "1" ] && exit 1
+          set flagctl=0
+          kubectl logs -l app=${{ env.DEPLOYMENT_NAME }} | grep -qEi 'fail|err' && (echo "found errors, proceeding to rollout..." && kubectl rollout undo deployment/${{ env.DEPLOYMENT_NAME }} && set flagctl=1) || (echo "No errors found in logs.")
+          echo "$flagctl"
+          echo $flagctl
+          echo [ "$flagctl" = "1" ]
+          [ "$flagctl" = "1" ] && exit 1
 
