unsabotage + fix exit code

diff --git a/.github/workflows/cicd-wkf.yml b/.github/workflows/cicd-wkf.yml
--- a/.github/workflows/cicd-wkf.yml
+++ b/.github/workflows/cicd-wkf.yml
@@ -128,10 +128,5 @@ jobs:
       - 
         name: Check container logs
         run: |
-          export flagctl="0"
-          kubectl logs -l app=${{ env.DEPLOYMENT_NAME }} | grep -qEi 'fail|err|Error' && (echo "found errors, proceeding to rollout..." && kubectl rollout undo deployment/${{ env.DEPLOYMENT_NAME }} && echo "rolled out" && export flagctl="1") || (echo "No errors found in logs.")
-          echo "$flagctl"
-          echo $flagctl
-          echo [ "$flagctl" = "1" ]
-          [ "$flagctl" = "1" ] && exit 1
+          kubectl logs -l app=${{ env.DEPLOYMENT_NAME }} | grep -qEi 'fail|err|Error' && (echo "found errors, proceeding to rollout..." && kubectl rollout undo deployment/${{ env.DEPLOYMENT_NAME }} && exit 1) || echo "No errors found in logs."
 
